# Generated by Django 3.2.14 on 2022-07-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail2',
            field=models.TextField(default=20220202, max_length=200),
            preserve_default=False,
        ),
    ]
