# Generated by Django 3.2.14 on 2022-07-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_detail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='detail2',
        ),
    ]
